apiVersion: v1
kind: Pod
metadata:
  name: holy-api
  namespace: pluto
  labels:
    id: holy-api
spec:
  template:
    metadata:
      labels:
        id: holy-api
        name: holy-api
  containers:
  - name: holy-api-container
    image: nginx:1.17.3-alpine
    env:
    - name: CACHE_KEY_1
      value: b&MTCi0=[T66RXm!jO@
    - name: CACHE_KEY_2
      value: PCAILGej5Ld@Q%{Q1=#
    - name: CACHE_KEY_3
      value: 2qz-]2OJlWDSTn_;RFQ
    volumeMounts:
    - name: cache-volume1
      mountPath: /cache1
    - name: cache-volume2
      mountPath: /cache2
    - name: cache-volume3
      mountPath: /cache3
  volumes:
  - name: cache-volume1
    emptyDir: {}
  - name: cache-volume2
    emptyDir: {}
  - name: cache-volume3
    emptyDir: {}
